github.com:
    users:
        Kokecoco:
            oauth_token: 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
    git_protocol: ssh
    oauth_token: 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
    user: Kokecoco
